a=float(input('Enter 1st number = '))
b=float(input('Enter 2nd number = '))
print("Addition = ",a+b)
print("Substraction = ",a-b)
print("Multiplication = ",a*b)
print("Division = ",a/b)
print("Floar Division = ",a+b) 